version: "3.5"

services:
  db:
    image: postgres:12-alpine
    command: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=erp
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - '6379:6379'

volumes:
  pg_data:
